id: IFA80CDF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:41:38+00:00'
last_modified: '2022-06-08T08:50:16.346051+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24019
  title: སྡེ་དགེ་རྒྱལ་རབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8E33:
      image_group_id: I1KG24079
      title: ''
      total_pages: 102
      order: 1
      base_file: 8E33.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
